// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type OverflowCreateData struct {
	DistributorDeliveryId string `json:"distributorDeliveryId"` // 配送订单ID
}

type OverflowCreateRequest struct {
	DeliveryId      string `json:"deliveryId"`             // 上游订单号
	SendType        int    `json:"sendType"`               // 订单小类 0帮我送 1帮我买 2帮我取
	Sender          string `json:"sender"`                 // 发货人姓名
	SenderPhone     string `json:"senderPhone"`            // 发货人联系电话
	FromAddress     string `json:"fromAddress"`            // 发货地址
	FromUserNote    string `json:"fromUserNote,optional"`  // 发货地址具体门牌号或门店名称
	FromLat         string `json:"fromLat"`                // 发货地址坐标纬度
	FromLng         string `json:"fromLng"`                // 发货地址坐标经度
	Receiver        string `json:"receiver"`               // 收件人姓名
	ReceiverPhone   string `json:"receiverPhone"`          // 收件人联系电话
	ToAddress       string `json:"toAddress"`              // 收货人地址
	ToUserNote      string `json:"toUserNote"`             // 收货人具体门牌号
	ToLat           string `json:"toLat"`                  // 收货地址坐标纬度
	ToLng           string `json:"toLng"`                  // 收货地址坐标经度
	Note            string `json:"note,optional"`          // 备注
	CityName        string `json:"cityName"`               // 订单所在城市名称
	CountyName      string `json:"countyName,optional"`    // 订单所在县级地名称
	SubscribeType   string `json:"subscribeType"`          // 预约类型 0 实时单
	SubscribeTime   string `json:"subscribeTime,optional"` // 预约时间时间戳
	GoodsWeight     string `json:"goodsWeight,optional"`   // 物品重量单位：KG
	OriginalPrice   string `json:"originalPrice"`          // 商品价格 原价(元)
	Price           string `json:"price"`                  // 商品价格 实际支付金额(元)
	ProductDetail   string `json:"productDetail,optional"` // 商品列表 json格式
	GoodsClass      int    `json:"goodsClass"`             // 商品类型 枚举值
	QuotationPrice  string `json:"quotationPrice"`         // 报价，元
	DeliveryType    string `json:"deliveryType"`           // 1：团送 2专送
	OrderSource     string `json:"orderSource"`            // 订单来源 枚举值
	OrderNum        string `json:"orderNum"`               // 订单流水号
	IsInsurance     int    `json:"is_insurance"`           // 是否保价 1 是 0 否
	DisableDelivery string `json:"disableDelivery"`        // 禁用配送方
	SfStoreId       string `json:"sf_store_id,optional"`   // 顺丰门店id
}

type OverflowCreateResponse struct {
	Code int                  `json:"code"` // 错误码 0成功
	Msg  string               `json:"msg"`  // 消息
	Data []OverflowCreateData `json:"data"` // 返回数据
}

type ProductDetailItem struct {
	GoodsName string `json:"goods_name"`         // 商品名称
	GoodsNum  string `json:"goods_num,optional"` // 商品数量
	Price     string `json:"price,optional"`     // 商品价格 单位元
	Unit      string `json:"unit,optional"`      // 商品规格
	Weight    string `json:"weight,optional"`    // 商品重量 单位克
	GoodsImg  string `json:"goods_img,optional"` // 商品图片
}

type SfOverflowCreateData struct {
	DeliveryOrderId string `json:"deliveryOrderId"` // 配送订单ID
	OrderId         string `json:"orderId"`         // 订单ID
}

type SfOverflowCreateRequest struct {
	OrderNo           string `json:"orderNo"`           // 顺丰同城订单号
	SourceOrderNo     string `json:"sourceOrderNo"`     // 来源订单号（如美团订单号）
	Source            string `json:"source"`            // 订单来源标识
	OrderSn           string `json:"orderSn"`           // 订单序号
	AdCode            string `json:"adCode"`            // 城市编码 例:110000，高德城市编码规范
	OrderTime         string `json:"orderTime"`         // 订单时间(如："2023-04-27 11:03:25")
	FromId            string `json:"fromId"`            // 发方唯一ID（店铺ID/用户ID）
	FromName          string `json:"fromName"`          // 发方名称
	FromPhone         string `json:"fromPhone"`         // 发方电话
	FromAddress       string `json:"fromAddress"`       // 发方地址详细到门牌号
	FromAddressDetail string `json:"fromAddressDetail"` // 发方详址详细到楼栋门牌
	FromLatitude      string `json:"fromLatitude"`      // 发方纬度
	FromLongitude     string `json:"fromLongitude"`     // 发方经度
	ToName            string `json:"toName"`            // 收方名称
	ToPhone           string `json:"toPhone"`           // 收方电话
	ToAddress         string `json:"toAddress"`         // 收方地址
	ToAddressDetail   string `json:"toAddressDetail"`   // 收方详址
	ToLatitude        string `json:"toLatitude"`        // 收方纬度
	ToLongitude       string `json:"toLongitude"`       // 收方经度
	OrderRemark       string `json:"orderRemark"`       // 备注
	IsSubscribe       string `json:"isSubscribe"`       // 是否预约单 0否1是
	SubscribeTime     string `json:"subscribeTime"`     // 预约送达时间 （毫秒级别）
	GoodType          string `json:"goodType"`          // 物品类型
	TotalAmount       string `json:"totalAmount"`       // 货品总值
	GoodsCount        string `json:"goodsCount"`        // 货品数量
	Weight            string `json:"weight"`            // 总重量 必须大于0,单位g
	PostPrice         string `json:"postPrice"`         // 发单价格 (分)（包含小费)
	IsInsured         string `json:"isInsured"`         // 是否保价 0否1是
	IsPersonDirect    string `json:"isPersonDirect"`    // 是否专人直送 0否1是
	OrderTip          string `json:"orderTip"`          // 订单小费 单位分
	WeatherLevel      string `json:"weatherLevel"`      // 天气等级
	PriceDistance     string `json:"priceDistance"`     // 计价距离 单位米
	IsCityShop        string `json:"isCityShop"`        // 是否是城市型店铺1是，0否
	IsReverseOrder    string `json:"isReverseOrder"`    // 是否是帮我取订单 1是，0否
	Goods             string `json:"goods"`             // name 名称 qty 数量 amount 价格单位分
}

type SfOverflowCreateResponse struct {
	Data   SfOverflowCreateData `json:"data"`
	Errno  int                  `json:"errno"`  // 错误码
	Errmsg string               `json:"errmsg"` // 错误信息
}

type UUCancelOrderRequest struct {
	DeliveryId string `json:"deliveryId"` // UU订单号
	Reason     string `json:"reason"`     // 取消原因
}

type UUCreateOrderRequest struct {
	DeliveryId      string `json:"deliveryId"`               // 上游订单号
	SendType        int    `json:"sendType"`                 // 订单小类 0帮我送 1帮我买 2帮我取
	Sender          string `json:"sender"`                   // 发货人姓名
	SenderPhone     string `json:"senderPhone"`              // 发货人联系电话
	FromAddress     string `json:"fromAddress"`              // 发货地址
	FromUserNote    string `json:"fromUserNote,optional"`    // 发货详细地址具体门牌号或门店名称
	FromLat         string `json:"fromLat"`                  // 发货地址坐标纬度(高德地图坐标系)
	FromLng         string `json:"fromLng"`                  // 发货地址坐标经度(高德地图坐标系)
	Receiver        string `json:"receiver"`                 // 收件人姓名
	ReceiverPhone   string `json:"receiverPhone"`            // 收件人联系电话
	ToAddress       string `json:"toAddress"`                // 收货人地址
	ToUserNote      string `json:"toUserNote"`               // 收货人详细地址具体门牌号
	ToLat           string `json:"toLat"`                    // 收货地址坐标纬度(高德地图坐标系)
	ToLng           string `json:"toLng"`                    // 收货地址坐标经度(高德地图坐标系)
	Note            string `json:"note,optional"`            // 备注
	CityName        string `json:"cityName"`                 // 订单所在城市名称(如"郑州市")
	CountyName      string `json:"countyName,optional"`      // 订单所在县级地名称
	PushType        string `json:"pushType"`                 // 推送方式（0 正常订单，1测试订单）
	SubscribeType   string `json:"subscribeType"`            // 预约类型 0 实时单 1 预约取件时间 2 预约送达时间
	SubscribeTime   string `json:"subscribeTime,optional"`   // 预约时间时间戳（秒）
	GoodsWeight     string `json:"goodsWeight,optional"`     // 物品重量单位：KG
	OriginalPrice   string `json:"originalPrice"`            // 商品价格 原价(元)
	Price           string `json:"price"`                    // 商品价格 实际支付金额(元)
	ProductDetail   string `json:"productDetail,optional"`   // 商品列表
	GoodsPrice      int    `json:"goodsPrice,optional"`      // 商品保价：价格（1-10000）
	GoodsType       string `json:"goodsType"`                // 商品类型(废弃)
	GoodsClass      int    `json:"goodsClass"`               // 商品类型 枚举值
	QuotationPrice  string `json:"quotationPrice"`           // 报价，元
	DeliveryType    string `json:"deliveryType"`             // 1：团送 2专送
	OrderSource     string `json:"orderSource"`              // 订单来源 枚举值
	OrderNum        string `json:"orderNum"`                 // 订单流水号
	IsDeliveryImg   int    `json:"isDeliveryImg,optional"`   // 是否需要妥投照片 0 否 1是
	DisableDelivery string `json:"disableDelivery,optional"` // 运力屏蔽，多个配送平台通过英文逗号分隔
}

type UUOrderResponse struct {
	Code      string `json:"code"`      // 错误码 0成功
	Msg       string `json:"msg"`       // 消息
	Data      string `json:"data"`      // 无
	RequestId string `json:"requestId"` // 无
}
