// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gatewayPlatformConfigFieldNames          = builder.RawFieldNames(&GatewayPlatformConfig{})
	gatewayPlatformConfigRows                = strings.Join(gatewayPlatformConfigFieldNames, ",")
	gatewayPlatformConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(gatewayPlatformConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gatewayPlatformConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(gatewayPlatformConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCdtsDeliveryDbGatewayPlatformConfigIdPrefix    = "cache:cdtsDeliveryDb:gatewayPlatformConfig:id:"
	cacheCdtsDeliveryDbGatewayPlatformConfigAppIdPrefix = "cache:cdtsDeliveryDb:gatewayPlatformConfig:appId:"
)

type (
	gatewayPlatformConfigModel interface {
		Insert(ctx context.Context, data *GatewayPlatformConfig) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GatewayPlatformConfig, error)
		FindOneByAppId(ctx context.Context, appId string) (*GatewayPlatformConfig, error)
		Update(ctx context.Context, data *GatewayPlatformConfig) error
	}

	defaultGatewayPlatformConfigModel struct {
		sqlc.CachedConn
		table string
	}

	GatewayPlatformConfig struct {
		Id           uint64    `db:"id"`
		AppName      string    `db:"app_name"`
		AppId        string    `db:"app_id"`
		AppSecret    string    `db:"app_secret"`    // 应用Secret
		PlatformCode string    `db:"platform_code"` // 平台编码
		WebhookUrl   string    `db:"webhook_url"`   // 回调地址
		Status       int64     `db:"status"`        // 状态：1启用 0禁用
		Remark       string    `db:"remark"`        // 备注
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newGatewayPlatformConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGatewayPlatformConfigModel {
	return &defaultGatewayPlatformConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`gateway_platform_config`",
	}
}

func (m *defaultGatewayPlatformConfigModel) FindOne(ctx context.Context, id uint64) (*GatewayPlatformConfig, error) {
	cdtsDeliveryDbGatewayPlatformConfigIdKey := fmt.Sprintf("%s%v", cacheCdtsDeliveryDbGatewayPlatformConfigIdPrefix, id)
	var resp GatewayPlatformConfig
	err := m.QueryRowCtx(ctx, &resp, cdtsDeliveryDbGatewayPlatformConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gatewayPlatformConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGatewayPlatformConfigModel) FindOneByAppId(ctx context.Context, appId string) (*GatewayPlatformConfig, error) {
	cdtsDeliveryDbGatewayPlatformConfigAppIdKey := fmt.Sprintf("%s%v", cacheCdtsDeliveryDbGatewayPlatformConfigAppIdPrefix, appId)
	var resp GatewayPlatformConfig
	err := m.QueryRowIndexCtx(ctx, &resp, cdtsDeliveryDbGatewayPlatformConfigAppIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `app_id` = ? limit 1", gatewayPlatformConfigRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, appId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGatewayPlatformConfigModel) Insert(ctx context.Context, data *GatewayPlatformConfig) (sql.Result, error) {
	cdtsDeliveryDbGatewayPlatformConfigAppIdKey := fmt.Sprintf("%s%v", cacheCdtsDeliveryDbGatewayPlatformConfigAppIdPrefix, data.AppId)
	cdtsDeliveryDbGatewayPlatformConfigIdKey := fmt.Sprintf("%s%v", cacheCdtsDeliveryDbGatewayPlatformConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, gatewayPlatformConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AppName, data.AppId, data.AppSecret, data.PlatformCode, data.WebhookUrl, data.Status, data.Remark)
	}, cdtsDeliveryDbGatewayPlatformConfigAppIdKey, cdtsDeliveryDbGatewayPlatformConfigIdKey)
	return ret, err
}

func (m *defaultGatewayPlatformConfigModel) Update(ctx context.Context, newData *GatewayPlatformConfig) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	cdtsDeliveryDbGatewayPlatformConfigAppIdKey := fmt.Sprintf("%s%v", cacheCdtsDeliveryDbGatewayPlatformConfigAppIdPrefix, data.AppId)
	cdtsDeliveryDbGatewayPlatformConfigIdKey := fmt.Sprintf("%s%v", cacheCdtsDeliveryDbGatewayPlatformConfigIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gatewayPlatformConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AppName, newData.AppId, newData.AppSecret, newData.PlatformCode, newData.WebhookUrl, newData.Status, newData.Remark, newData.Id)
	}, cdtsDeliveryDbGatewayPlatformConfigAppIdKey, cdtsDeliveryDbGatewayPlatformConfigIdKey)
	return err
}

func (m *defaultGatewayPlatformConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCdtsDeliveryDbGatewayPlatformConfigIdPrefix, primary)
}

func (m *defaultGatewayPlatformConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gatewayPlatformConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGatewayPlatformConfigModel) tableName() string {
	return m.table
}
