// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	chd "chuandao-sails-core/apps/upstream-push/api/internal/handler/chd"
	sf "chuandao-sails-core/apps/upstream-push/api/internal/handler/sf"
	uu "chuandao-sails-core/apps/upstream-push/api/internal/handler/uu"
	"chuandao-sails-core/apps/upstream-push/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 订单创建
				Method:  http.MethodPost,
				Path:    "/platform/callback/overflow/create",
				Handler: chd.OverflowCreateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 订单创建
				Method:  http.MethodPost,
				Path:    "/platform/sf/overflow/create",
				Handler: sf.SfOverflowCreateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 接收取消订单消息
				Method:  http.MethodPost,
				Path:    "/platform/callback/uuQuotation/cancel",
				Handler: uu.CancelOrderHandler(serverCtx),
			},
			{
				// 接收订单
				Method:  http.MethodPost,
				Path:    "/platform/callback/uuQuotation/create",
				Handler: uu.CreateOrderHandler(serverCtx),
			},
		},
	)
}
