package constants

// 配送平台类型枚举 (deliveryType字段)
const (
	DELIVERY_PLATFORM_SHIP_TO    = 0  // 船到
	DELIVERY_PLATFORM_UU         = 1  // UU跑腿
	DELIVERY_PLATFORM_DADA       = 2  // 达达快送
	DELIVERY_PLATFORM_SF         = 3  // 顺丰
	DELIVERY_PLATFORM_FLASH      = 4  // 闪送
	DELIVERY_PLATFORM_SOGO       = 5  // 搜果小递
	DELIVERY_PLATFORM_FENGNIAO   = 6  // 蜂鸟跑腿
	DELIVERY_PLATFORM_KUAIFUWU   = 9  // 快服务
	DELIVERY_PLATFORM_AIPAOTUI   = 14 // 爱跑腿
	DELIVERY_PLATFORM_DADA_QUICK = 19 // 达达急送
	DELIVERY_PLATFORM_KUAIDA     = 30 // 快达
	DELIVERY_PLATFORM_MEITUAN    = 31 // 美团快递达
	DELIVERY_PLATFORM_KUAIMA     = 32 // 快马跑腿
	DELIVERY_PLATFORM_SF_EXPRESS = 33 // 顺丰优享
	DELIVERY_PLATFORM_JIESHU     = 45 // 街顺
	DELIVERY_PLATFORM_CANDO      = 47 // 餐道
	DELIVERY_PLATFORM_KUAILAIDA  = 48 // 快来送
	DELIVERY_PLATFORM_TUANPAOTUI = 49 // 团跑腿
	DELIVERY_PLATFORM_YOUPAIDA   = 50 // 优派达
)

// 配送平台名称映射
var DeliveryPlatformNames = map[int]string{
	DELIVERY_PLATFORM_SHIP_TO:    "船到",
	DELIVERY_PLATFORM_UU:         "UU跑腿",
	DELIVERY_PLATFORM_DADA:       "达达快送",
	DELIVERY_PLATFORM_SF:         "顺丰",
	DELIVERY_PLATFORM_FLASH:      "闪送",
	DELIVERY_PLATFORM_SOGO:       "搜果小递",
	DELIVERY_PLATFORM_FENGNIAO:   "蜂鸟跑腿",
	DELIVERY_PLATFORM_KUAIFUWU:   "快服务",
	DELIVERY_PLATFORM_AIPAOTUI:   "爱跑腿",
	DELIVERY_PLATFORM_DADA_QUICK: "达达急送",
	DELIVERY_PLATFORM_KUAIDA:     "快达",
	DELIVERY_PLATFORM_MEITUAN:    "美团快递达",
	DELIVERY_PLATFORM_KUAIMA:     "快马跑腿",
	DELIVERY_PLATFORM_SF_EXPRESS: "顺丰优享",
	DELIVERY_PLATFORM_JIESHU:     "街顺",
	DELIVERY_PLATFORM_CANDO:      "餐道",
	DELIVERY_PLATFORM_KUAILAIDA:  "快来送",
	DELIVERY_PLATFORM_TUANPAOTUI: "团跑腿",
	DELIVERY_PLATFORM_YOUPAIDA:   "优派达",
}
