// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"chuandao-sails-core/demo/restful/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.HTTPLogMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/from/:name",
					Handler: UserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/hello",
					Handler: HelloHandler(serverCtx),
				},
			}...,
		),
	)
}
