// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddTipReq struct {
	SignType
	OrderNo   string `json:"order_no"`   // 订单号
	TipAmount int64  `json:"tip_amount"` // 小费金额 分
}

type AddTipResp struct {
	OrderNo    string           `json:"order_no"`
	AddTipList []DeliveryAddTip `json:"add_tip_list"`
}

type Address struct {
	Lng    string `json:"lng"`
	Lat    string `json:"lat"`
	Detail string `json:"detail"`
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
}

type CancelOrderReq struct {
	SignType
	OrderNo string `json:"order_no"`
}

type CancelOrderResp struct {
	OrderNO         string                `json:"order_no"`
	CancelOrderList []DeliveryCancelOrder `json:"cancel_order_list"`
}

type Delivery struct {
	DeliveryCode string `json:"delivery_code"`
	DeliveryName string `json:"delivery_name"`
}

type DeliveryAddTip struct {
	Delivery
	Return
}

type DeliveryCancelOrder struct {
	Delivery
	PenaltyFee int64 `json:"penalty_fee"` //违约金
}

type DeliveryDispatch struct {
	Delivery
	DeliveryOrderNo string `json:"delivery_order_no"` //配送平台单号
}

type DeliveryPenalty struct {
	Delivery
	Return
	PenaltyFee int64 `json:"penalty_fee"` //违约金
}

type DeliveryQuota struct {
	Delivery
	Price     int64  `json:"price"`     // 配送费 分
	Distance  int64  `json:"distance"`  // 距离 米
	Available int64  `json:"available"` // 是否可接单
	Reason    string `json:"reason"`    // 不可用原因
}

type DispatchOrderReq struct {
	SignType
	OrderNO      string `json:"order_no"`
	DeliveryCode string `json:"delivery_code",optional` // 指定平台，默认询价出来的全部
	CallbackUrl  string `json:"callback_url",optional`  //状态回调地址
}

type DispatchOrderResp struct {
	OrderNo      string             `json:"order_no"`
	DispatchList []DeliveryDispatch `json:"dispatch_list"`
}

type DriverInfo struct {
	Name    string `json:"name"`
	Mobile  string `json:"mobile"`
	LastLng string `json:"last_lng"`
	LastLat string `json:"last_lat"`
}

type EmptyType struct {
}

type FeeInfo struct {
	QueryPrice  int64   `json:"query_price"`  //询价报价 分
	ActualPrice int64   `json:"actual_price"` //实际发单价格
	TipAmount   int64   `json:"tip_amount"`   //小费
	PenaltyFee  float64 `json:"penalty_fee"`  //违约金
	TotalFee    int64   `json:"total_fee"`    //总计
}

type GetCancelFeeResp struct {
	OrderNo     string            `json:"order_no"`
	PenaltyList []DeliveryPenalty `json:"penalty_list"`
}

type GetDriverLocResp struct {
	SignType
	Delivery
	OrderNO         string      `json:"order_no"`
	DeliveryOrderNo string      `json:"delivery_order_no"`
	DriverInfo      *DriverInfo `json:"driver_info,optional"`
}

type GetQuotaReq struct {
	SignType
	OriginOrderId   string      `json:"origin_order_id"`   //对接方订单号
	UpstreamSoucre  string      `json:"upstream_soucre"`   //推单平台
	UpstreamOrderId string      `json:"upstream_order_id"` //推单平台订单号
	ShortNum        int64       `json:"short_num"`         //取餐号
	GoodInfo        []GoodsList `json:"goodInfo"`          //商品详细信息列表
	Note            string      `json:"note",optional`     //下单备注
	FromAddress     Address     `json:"from_address"`      //发货地址
	ToAddress       Address     `json:"to_address"`        //收货地址
	GoodsType       int64       `json:"goods_type"`        //物品类型
	GoodsWeight     float64     `json:"goods_weight"`      //物品重量
	SubscribeType   int64       `json:"subscribe_type"`    //预约类型：0实时 1预约取件 2预约送达
	SubscribeTime   string      `json:"subscribe_time"`    //预约时间戳
	SelectDelivery  string      `json:"select_delivery"`   //选择运力 1,2,3
}

type GetQuotaResp struct {
	OrderNO   string          `json:"order_no"`
	QuotaList []DeliveryQuota `json:"quota_list"` //各平台报价
}

type GoodsList struct {
	GoodsName string `json:"goods_name"` //商品名称
	GoodsNum  int64  `json:"goods_num"`  //数量
}

type QueryOrderReq struct {
	SignType
	OrderNO string `path:"order_no"`
}

type QueryOrderResp struct {
	Delivery
	OrderNO         string      `json:"order_no"`
	DeliveryOrderNo string      `json:"delivery_order_no"`    //配送订单号
	Status          string      `json:"status"`               // 订单状态
	Note            string      `json:"note"`                 // 订单备注
	DriverInfo      *DriverInfo `json:"driver_info,optional"` //骑手信息
	FeeInfo         *FeeInfo    `json:"fee_info"`
	TimeLine        []TimeLine  `json:"time_line"` //时间线信息
	FromAddress     Address     `json:"from_address"`
	ToAddress       Address     `json:"to_address"`
}

type Return struct {
	Success string `json:"success"`          //平台状态
	Message string `json:"message",optional` //平台返回信息
}

type SignType struct {
	AppId     string `json:"appId"`
	Timestamp string `json:"timestamp"`
	Data      string `json:"data"`
	Sign      string `json:"sign"`
}

type TimeLine struct {
	Time       int64  `json:"time"`
	StatusNode string `json:"status_node"` //发单/预计到达/达到/完成 时间
}
