// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"chuandao-sails-core/app/api/delivery/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.HTTPLogMiddleware, serverCtx.SignMiddleware},
			[]rest.Route{
				{
					// 加小费
					Method:  http.MethodPost,
					Path:    "/AddTip",
					Handler: addTipHandler(serverCtx),
				},
				{
					// 取消订单
					Method:  http.MethodPost,
					Path:    "/CancelOrder",
					Handler: cancelOrderHandler(serverCtx),
				},
				{
					// 查询运费后下单
					Method:  http.MethodPost,
					Path:    "/DispatchOrder",
					Handler: dispatchOrderHandler(serverCtx),
				},
				{
					// 查询取消订单费用
					Method:  http.MethodPost,
					Path:    "/GetCancelFee",
					Handler: getCancelFeeHandler(serverCtx),
				},
				{
					// 查看跑男位置
					Method:  http.MethodGet,
					Path:    "/GetDriverLocation/:order_no",
					Handler: getDriverLocationHandler(serverCtx),
				},
				{
					// 查询运费
					Method:  http.MethodPost,
					Path:    "/GetQuote",
					Handler: getQuoteHandler(serverCtx),
				},
				{
					// 查询订单详情
					Method:  http.MethodGet,
					Path:    "/QueryOrder/:order_no",
					Handler: queryOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/delivery"),
	)
}
