// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	uu "chuandao-sails-core/apps/delivery-dispatch/api/callback/internal/handler/uu"
	"chuandao-sails-core/apps/delivery-dispatch/api/callback/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 订单状态回调，用户提交订单时传入
				Method:  http.MethodPost,
				Path:    "/state",
				Handler: uu.UuCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/callback/uu"),
	)
}
