CREATE TABLE `dispatch_retry_log`
(
    `id`                bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `delivery_no`       varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送单号',
    `external_order_no` varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '外部订单号',
    `platform_code`     varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送平台代码',
    `platform_order_no` varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '平台订单号',
    `retry_type`        varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '重试类型：INQUIRY/DISPATCH/CANCEL/QUERY/ADD_FEE',
    `retry_count`       tinyint                                  NOT NULL DEFAULT 0 COMMENT '第几次重试',
    `max_retry`         tinyint                                  NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    `retry_reason`      varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '重试原因',
    `retry_strategy`    varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT 'EXPONENTIAL' COMMENT '重试策略：IMMEDIATE/FIXED/EXPONENTIAL',
    `retry_interval`    int                                      NOT NULL DEFAULT 0 COMMENT '重试间隔（秒）',
    `is_success`        tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否成功：1成功 0失败',
    `duration`          int                                      NOT NULL DEFAULT 0 COMMENT '耗时（毫秒）',
    `request_data`      json                                     NOT NULL DEFAULT '{}' COMMENT '请求数据',
    `response_data`     json                                     NOT NULL DEFAULT '{}' COMMENT '响应数据',
    `error_code`        varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '错误码',
    `error_msg`         varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '错误信息',
    `error_type`        varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '错误类型：TIMEOUT/NETWORK/BUSINESS/PLATFORM',
    `next_retry_time`   datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '下次重试时间',
    `is_final_retry`    tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否最后一次重试：1是 0否',
    `final_status`      varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '最终状态：SUCCESS/FAILED/ABANDONED',
    `extra_data`        json                                     NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `city_code`         varchar(20) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市编码',
    `created_at`        datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY                 `idx_delivery_no` (`delivery_no`, `created_at`),
    KEY                 `idx_external_order` (`external_order_no`),
    KEY                 `idx_platform_code` (`platform_code`),
    KEY                 `idx_retry_type` (`retry_type`),
    KEY                 `idx_is_success` (`is_success`),
    KEY                 `idx_final_status` (`final_status`),
    KEY                 `idx_next_retry_time` (`next_retry_time`),
    KEY                 `idx_city_created` (`city_code`, `created_at`),
    KEY                 `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='发单重试记录表';