CREATE TABLE `dispatch_inquiry_detail`
(
    `id`                bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `inquiry_id`        varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '询价ID',
    `external_order_no` varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '外部订单号',
    `platform_code`     varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '平台代码',
    `platform_name`     varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '平台名称',
    `is_success`        tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否成功:1成功0失败',
    `is_available`      tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否可用:1可用0不可用',
    `inquiry_price`     decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '询价价格(元)',
    `origin_price`      decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '原价(元)',
    `distance_fee`      decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '距离费用(元)',
    `weight_fee`        decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '重量费用(元)',
    `time_fee`          decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '时段费用(元)',
    `platform_fee`      decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '平台费用(元)',
    `estimated_time`    int                                      NOT NULL DEFAULT 0 COMMENT '预计送达时长(分钟)',
    `distance`          decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '配送距离(公里)',
    `duration`          int                                      NOT NULL DEFAULT 0 COMMENT '询价耗时(毫秒)',
    `request_data`      json                                     NOT NULL DEFAULT '{}' COMMENT '请求数据',
    `response_data`     json                                     NOT NULL DEFAULT '{}' COMMENT '响应数据',
    `error_code`        varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '错误码',
    `error_msg`         varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '错误信息',
    `sort_score`        decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '排序分数(价格/时效综合)',
    `rank`              int                                      NOT NULL DEFAULT 0 COMMENT '排名',
    `extra_data`        json                                     NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `city_code`         varchar(20) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市编码',
    `created_at`        datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY                 `idx_inquiry_id` (`inquiry_id`, `created_at`),
    KEY                 `idx_external_order` (`external_order_no`),
    KEY                 `idx_platform_success` (`platform_code`, `is_success`, `created_at`),
    KEY                 `idx_available_rank` (`is_available`, `rank`),
    KEY                 `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='询价明细表';