CREATE TABLE `dispatch_order`
(
    `id`                bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_no`          varchar(255) NOT NULL COMMENT '系统单号',
    `origin_order_id`   varchar(255) NOT NULL COMMENT '对接第三方的订单号',
    `upstream_source`   varchar(255) NOT NULL COMMENT '上游推单来源',
    `upstream_order_id` varchar(255) NOT NULL COMMENT '上游平台订单号',
    `delivery_code`     varchar(32) NOT NULL COMMENT '配送平台代码：UU/DD',
    `delivery_order_no` varchar(255) NOT NULL DEFAULT '' COMMENT '配送订单号',
    `short_num`         int NOT NULL COMMENT '取餐号',
    `account_id`        int NOT NULL COMMENT '使用账号',
    `source_app_id`     varchar(100) NOT NULL COMMENT '来源appid',
    `inquiry_id`        bigint NOT NULL COMMENT '询价记录ID',
    `status`            varchar(32) NOT NULL DEFAULT 'CREATED' COMMENT '订单状态',
    `from_mobile`       varchar(255) NOT NULL COMMENT '发货手机号',
    `from_address`      json NOT NULL COMMENT '起点地址',
    `to_mobile`         varchar(255) NOT NULL COMMENT '收货手机号',
    `to_address`        json NOT NULL COMMENT '终点地址',
    `note`              varchar(255) NOT NULL DEFAULT '' COMMENT '下单备注',
    `goods_name`        varchar(128) NOT NULL DEFAULT '' COMMENT '货物名称',
    `goods_type`        int NOT NULL DEFAULT 0 COMMENT '商品类型',
    `goods_detail`      json NOT NULL COMMENT '货物详情',
    `total_amount`      int NOT NULL DEFAULT 0 COMMENT '发单价格(分)',
    `price_detail`      json NOT NULL COMMENT '价格详情',
    `distance`          int NOT NULL DEFAULT 0 COMMENT '配送距离(米)',
    `driver_name`       varchar(255) NOT NULL DEFAULT '' COMMENT '配送员',
    `driver_mobile`     varchar(255) NOT NULL DEFAULT '' COMMENT '配送员电话',
    `shop_id`           int NOT NULL COMMENT '门店ID',
    `subscribe_type`    int NOT NULL DEFAULT 0 COMMENT '预约类型',
    `subscribe_time`    varchar(255) NOT NULL DEFAULT '0' COMMENT '预计时间',
    `disable_delivery`  varchar(255) NOT NULL DEFAULT '' COMMENT '禁用运力',
    `created_at`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_delivery_order` (`delivery_code`, `delivery_order_no`),
    KEY `idx_created_at` (`created_at`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配送订单主表';