CREATE TABLE `dispatch_inquiry_log`
(
    `id`                   bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `inquiry_id`           varchar(64) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '询价ID(系统生成)',
    `external_order_no`    varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '外部订单号',
    `business_no`          varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '业务流水号',
    `source_system`        varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '来源系统',
    `source_type`          varchar(16) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT 'API' COMMENT '来源类型:API/MQ/RPC',
    `city_name`            varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '城市名称',
    `city_code`            varchar(20) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '城市编码',
    `from_address`         json                                    NOT NULL DEFAULT '{}' COMMENT '起点地址',
    `to_address`           json                                    NOT NULL DEFAULT '{}' COMMENT '终点地址',
    `distance`             decimal(10, 2)                          NOT NULL DEFAULT 0.00 COMMENT '配送距离(公里)',
    `goods_name`           varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '货物名称',
    `goods_weight`         decimal(10, 2)                          NOT NULL DEFAULT 0.00 COMMENT '货物重量(公斤)',
    `goods_info`           json                                    NOT NULL DEFAULT '{}' COMMENT '货物详情',
    `expect_pickup_time`   datetime                                NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '期望取件时间',
    `expect_delivery_time` datetime                                NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '期望送达时间',
    `platform_count`       int                                     NOT NULL DEFAULT 0 COMMENT '询价平台数量',
    `success_count`        int                                     NOT NULL DEFAULT 0 COMMENT '成功返回数量',
    `fail_count`           int                                     NOT NULL DEFAULT 0 COMMENT '失败数量',
    `best_platform_code`   varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '最优平台代码',
    `best_price`           decimal(10, 2)                          NOT NULL DEFAULT 0.00 COMMENT '最优价格(元)',
    `avg_price`            decimal(10, 2)                          NOT NULL DEFAULT 0.00 COMMENT '平均价格(元)',
    `min_price`            decimal(10, 2)                          NOT NULL DEFAULT 0.00 COMMENT '最低价格(元)',
    `max_price`            decimal(10, 2)                          NOT NULL DEFAULT 0.00 COMMENT '最高价格(元)',
    `total_duration`       int                                     NOT NULL DEFAULT 0 COMMENT '总耗时(毫秒)',
    `is_dispatched`        tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已发单:1是0否',
    `dispatched_platform`  varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '实际发单平台',
    `extra_data`           json                                    NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `created_at`           datetime                                NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inquiry_id` (`inquiry_id`),
    KEY                    `idx_external_order` (`external_order_no`),
    KEY                    `idx_business_no` (`business_no`),
    KEY                    `idx_dispatched` (`is_dispatched`, `created_at`),
    KEY                    `idx_city_code` (`city_code`),
    KEY                    `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='询价记录表';