CREATE TABLE `dispatch_exception_log`
(
    `id`                bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `delivery_no`       varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送单号',
    `external_order_no` varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '外部订单号',
    `platform_code`     varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送平台代码',
    `platform_order_no` varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '平台订单号',
    `exception_type`    varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '异常类型:TIMEOUT/DISPATCH_FAIL/PLATFORM_ERROR/COURIER_REFUSE/ADDRESS_ERROR',
    `exception_level`   varchar(16) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT 'NORMAL' COMMENT '异常等级:LOW/NORMAL/HIGH/CRITICAL',
    `exception_code`    varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '异常码',
    `exception_message` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '异常描述',
    `exception_stack`   text COLLATE utf8mb4_unicode_ci          NOT NULL COMMENT '异常堆栈',
    `order_status`      varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '异常时订单状态',
    `operation_type`    varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '操作类型:INQUIRY/DISPATCH/CANCEL/QUERY/CALLBACK',
    `request_data`      json                                     NOT NULL DEFAULT '{}' COMMENT '请求数据',
    `response_data`     json                                     NOT NULL DEFAULT '{}' COMMENT '响应数据',
    `duration`          int                                      NOT NULL DEFAULT 0 COMMENT '耗时(毫秒)',
    `is_resolved`       tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已解决:1是0否',
    `resolved_by`       varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '解决人',
    `resolved_at`       datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '解决时间',
    `resolved_method`   varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '解决方法',
    `retry_count`       tinyint                                  NOT NULL DEFAULT 0 COMMENT '重试次数',
    `max_retry`         tinyint                                  NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    `next_retry_time`   datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '下次重试时间',
    `is_alerted`        tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已告警:1是0否',
    `alert_channel`     varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '告警渠道:SMS/EMAIL/DINGTALK/WECHAT',
    `alert_receiver`    varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '告警接收人',
    `extra_data`        json                                     NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `city_code`         varchar(20) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市编码',
    `created_at`        datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`        datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY                 `idx_delivery_no` (`delivery_no`),
    KEY                 `idx_external_order` (`external_order_no`),
    KEY                 `idx_exception_type_level` (`exception_type`, `exception_level`, `created_at`),
    KEY                 `idx_is_resolved` (`is_resolved`, `created_at`),
    KEY                 `idx_retry` (`is_resolved`, `retry_count`, `next_retry_time`),
    KEY                 `idx_alert` (`is_alerted`, `exception_level`, `created_at`),
    KEY                 `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配送异常记录表';