CREATE TABLE `dispatch_fee_add_log`
(
    `id`                     bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `delivery_no`            varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送单号',
    `external_order_no`      varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '外部订单号',
    `platform_code`          varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送平台代码',
    `platform_order_no`      varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '平台订单号',
    `fee_amount`             decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '追加小费金额(元)',
    `fee_type`               varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT 'ONLINE' COMMENT '小费类型:ONLINE/OFFLINE',
    `fee_reason`             varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '追加原因',
    `order_status`           varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '追加时订单状态',
    `original_price`         decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '原始价格(元)',
    `total_fee_before`       decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '追加前总小费(元)',
    `total_fee_after`        decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '追加后总小费(元)',
    `total_amount`           decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '追加后总金额(元)',
    `operator`               varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '操作人',
    `operator_type`          varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '操作类型:USER/SYSTEM/CUSTOMER_SERVICE',
    `operation_source`       varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '操作来源:API/WEB/MOBILE',
    `is_success`             tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否成功:1成功0失败',
    `platform_response_code` varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '平台响应码',
    `platform_response_msg`  varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '平台响应消息',
    `request_data`           json                                     NOT NULL DEFAULT '{}' COMMENT '请求数据',
    `response_data`          json                                     NOT NULL DEFAULT '{}' COMMENT '响应数据',
    `payment_status`         varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT 'PENDING' COMMENT '支付状态:PENDING/SUCCESS/FAILED',
    `payment_method`         varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '支付方式:ALIPAY/WECHAT/BALANCE',
    `payment_time`           datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '支付时间',
    `transaction_no`         varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '交易流水号',
    `retry_count`            tinyint                                  NOT NULL DEFAULT 0 COMMENT '重试次数',
    `extra_data`             json                                     NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `city_code`              varchar(20) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市编码',
    `created_at`             datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`             datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY                      `idx_delivery_no` (`delivery_no`),
    KEY                      `idx_external_order` (`external_order_no`),
    KEY                      `idx_platform_order` (`platform_code`, `platform_order_no`),
    KEY                      `idx_success_payment` (`is_success`, `payment_status`, `created_at`),
    KEY                      `idx_transaction_no` (`transaction_no`),
    KEY                      `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='追加小费记录表';