CREATE TABLE `dispatch_order`
(
    `id`                   bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `delivery_no`          varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送单号（系统唯一标识）',
    `external_order_no`    varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '外部订单号（调用方传入）',
    `business_no`          varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '业务流水号（调用方业务ID）',
    `source_system`        varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '来源系统：ERP/WMS/TMS/ORDER_SERVICE等',
    `source_type`          varchar(16) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT 'API' COMMENT '来源类型：API/MQ/RPC',
    `callback_url`         varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '回调地址（状态变更通知）',
    `platform_code`        varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送平台代码：UU/DADA/FENGNIAO/SHANSONG/SF等',
    `platform_order_no`    varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '平台订单号（发单后返回）',
    `status`               varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT 'CREATED' COMMENT '订单状态：CREATED/DISPATCHED/ASSIGNED/PICKED/DELIVERED/COMPLETED/CANCELLED',
    `status_desc`          varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '状态描述',
    `city_name`            varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市名称',
    `city_code`            varchar(20) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市编码',
    `from_address`         json                                     NOT NULL DEFAULT '{}' COMMENT '起点地址 {province,city,district,address,lat,lng,contact,phone}',
    `to_address`           json                                     NOT NULL DEFAULT '{}' COMMENT '终点地址 {province,city,district,address,lat,lng,contact,phone}',
    `distance`             decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '配送距离（公里）',
    `goods_name`           varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '货物名称',
    `goods_weight`         decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '货物重量（公斤）',
    `goods_info`           json                                     NOT NULL DEFAULT '{}' COMMENT '货物详情 {name,weight,quantity,value,remark}',
    `inquiry_price`        decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '询价价格（元）',
    `actual_price`         decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '实际价格（元）',
    `online_fee`           decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '追加小费（元）',
    `total_amount`         decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '总金额 = actual_price + online_fee',
    `expect_pickup_time`   datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '期望取件时间',
    `expect_delivery_time` datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '期望送达时间',
    `estimated_time`       int                                      NOT NULL DEFAULT 0 COMMENT '预计送达时长（分钟）',
    `pickup_time`          datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '实际取件时间',
    `delivered_time`       datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '实际送达时间',
    `completed_time`       datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '完成时间',
    `cancelled_time`       datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '取消时间',
    `courier_name`         varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '骑手姓名',
    `courier_phone`        varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '骑手电话',
    `courier_info`         json                                     NOT NULL DEFAULT '{}' COMMENT '骑手详情 {name,phone,lat,lng,avatar}',
    `cancel_reason_id`     varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '取消原因ID',
    `cancel_reason`        varchar(500) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '取消原因',
    `cancel_operator`      varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '取消操作人：PLATFORM/CLIENT/SYSTEM',
    `penalty_fee`          decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '违约金（元）',
    `remark`               varchar(500) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '订单备注',
    `internal_note`        varchar(500) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '内部备注（不传给平台）',
    `error_code`           varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '错误码',
    `error_msg`            varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '错误信息',
    `retry_count`          tinyint                                  NOT NULL DEFAULT 0 COMMENT '重试次数',
    `extra_data`           json                                     NOT NULL DEFAULT '{}' COMMENT '扩展数据（调用方自定义字段）',
    `created_by`           varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '创建人',
    `created_at`           datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`           datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_delivery_no` (`delivery_no`),
    KEY                    `idx_external_order` (`external_order_no`),
    KEY                    `idx_business_no` (`business_no`),
    KEY                    `idx_platform_order` (`platform_code`, `platform_order_no`),
    KEY                    `idx_status` (`status`),
    KEY                    `idx_source_system` (`source_system`),
    KEY                    `idx_city_created` (`city_code`, `created_at`),
    KEY                    `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配送订单主表';