CREATE TABLE `track_platform_callback_log`
(
    `id`                bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `trace_id`          varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '追踪ID',
    `callback_id`       varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '回调ID（平台提供）',
    `delivery_no`       varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送单号',
    `external_order_no` varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '外部订单号',
    `platform_code`     varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送平台代码',
    `platform_order_no` varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '平台订单号',
    `callback_type`     varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '回调类型：STATUS/LOCATION/EXCEPTION/TIMEOUT',
    `callback_event`    varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '回调事件：ORDER_ACCEPT/COURIER_ASSIGN/PICKUP/DELIVER等',
    `request_method`    varchar(16) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT 'HTTP方法：GET/POST',
    `request_url`       varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '请求URL',
    `request_headers`   json                                     NOT NULL DEFAULT '{}' COMMENT '请求头',
    `request_body`      text COLLATE utf8mb4_unicode_ci          NOT NULL COMMENT '请求体（原始数据）',
    `request_ip`        varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '请求IP',
    `signature`         varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '签名',
    `signature_type`    varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '签名类型：MD5/SHA256/HMAC',
    `verify_result`     tinyint(1) NOT NULL DEFAULT 0 COMMENT '签名验证结果：1成功 0失败',
    `verify_error`      varchar(500) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '验证错误信息',
    `business_data`     json                                     NOT NULL DEFAULT '{}' COMMENT '业务数据（解析后）',
    `order_status`      varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '订单状态',
    `courier_info`      json                                     NOT NULL DEFAULT '{}' COMMENT '骑手信息',
    `location_info`     json                                     NOT NULL DEFAULT '{}' COMMENT '位置信息',
    `is_processed`      tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已处理：1是 0否',
    `process_result`    varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '处理结果：SUCCESS/FAILED/IGNORED/DUPLICATE',
    `process_error`     varchar(500) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '处理错误信息',
    `process_duration`  int                                      NOT NULL DEFAULT 0 COMMENT '处理耗时（毫秒）',
    `processed_at`      datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '处理时间',
    `response_code`     int                                      NOT NULL DEFAULT 200 COMMENT 'HTTP响应码',
    `response_body`     varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '响应体',
    `is_duplicate`      tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否重复回调：1是 0否',
    `duplicate_count`   int                                      NOT NULL DEFAULT 0 COMMENT '重复次数',
    `extra_data`        json                                     NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `city_code`         varchar(20) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市编码',
    `created_at`        datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`        datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY                 `idx_trace_id` (`trace_id`),
    KEY                 `idx_callback_id` (`callback_id`),
    KEY                 `idx_delivery_no` (`delivery_no`, `created_at`),
    KEY                 `idx_external_order` (`external_order_no`),
    KEY                 `idx_platform_order` (`platform_code`, `platform_order_no`),
    KEY                 `idx_callback_type` (`callback_type`),
    KEY                 `idx_is_processed` (`is_processed`, `created_at`),
    KEY                 `idx_is_duplicate` (`is_duplicate`),
    KEY                 `idx_city_created` (`city_code`, `created_at`),
    KEY                 `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台回调日志表';