// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"chuandao-sails-core/apps/delivery-dispatch/api/v1/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Sign},
			[]rest.Route{
				{
					// 取消订单
					Method:  http.MethodPost,
					Path:    "/cancel",
					Handler: cancelOrderHandler(serverCtx),
				},
				{
					// 查询取消订单费用
					Method:  http.MethodPost,
					Path:    "/cancelFee",
					Handler: queryPenaltyHandler(serverCtx),
				},
				{
					// 查询运费后下单
					Method:  http.MethodPost,
					Path:    "/dispatch",
					Handler: dispatchOrderHandler(serverCtx),
				},
				{
					// 查看跑男位置
					Method:  http.MethodGet,
					Path:    "/dricker/:order_no",
					Handler: drickerTrackHandler(serverCtx),
				},
				{
					// 查询订单详情
					Method:  http.MethodGet,
					Path:    "/order/:order_no",
					Handler: queryOrderHandler(serverCtx),
				},
				{
					// 查询运费
					Method:  http.MethodPost,
					Path:    "/quote",
					Handler: priceQuoteHandler(serverCtx),
				},
				{
					// 加小费
					Method:  http.MethodPost,
					Path:    "/tip",
					Handler: addTipHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/delivery"),
	)
}
