// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddTipReq struct {
	SignType
	OrderNo   string `json:"order_no"`   // 订单号
	TipAmount int    `json:"tip_amount"` // 小费金额 分
}

type AddTipResp struct {
	OrderNo    string           `json:"order_no"`
	AddTipList []PlatformAddTip `json:"add_tip_list"`
}

type Address struct {
	Lng    string `json:"lng"`
	Lat    string `json:"lat"`
	Detail string `json:"detail"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
}

type CancelOrderReq struct {
	SignType
	OrderNo string `json:"order_no"`
}

type CancelOrderResp struct {
	OrderNO         string                `json:"order_no"`
	CancelOrderList []PlatformCancelOrder `json:"cancel_order_list"`
}

type DispatchOrderReq struct {
	SignType
	OrderNO      string `json:"order_no"`
	PlatformCode string `json:"platform_code"`         // 指定平台
	CallbackUrl  string `json:"callback_url",optional` //状态回调地址
}

type DispatchOrderResp struct {
	OrderNo      string             `json:"order_no"`
	DispatchList []PlatformDispatch `json:"dispatch_list"`
}

type DrickerTrackResp struct {
	SignType
	Platform
	OrderNO         string      `json:"order_no"`
	DeliveryOrderNo string      `json:"delivery_order_no"`
	DriverInfo      *DriverInfo `json:"driver_info,optional"`
}

type DriverInfo struct {
	Name    string  `json:"name"`
	Mobile  string  `json:"mobile"`
	LastLng float64 `json:"last_lng"`
	LastLat float64 `json:"last_lat"`
}

type FeeInfo struct {
	QueryPrice  int     `json:"query_price"`  //询价报价 分
	ActualPrice int     `json:"actual_price"` //实际发单价格
	TipAmount   int     `json:"tip_amount"`   //小费
	PenaltyFee  float64 `json:"penalty_fee"`  //违约金
	TotalFee    int     `json:"total_fee"`    //总计
}

type Platform struct {
	PlatformCode string `json:"platform_code"`
	PlatformName string `json:"platform_name"`
}

type PlatformAddTip struct {
	Platform
	Return
}

type PlatformCancelOrder struct {
	Platform
	PenaltyFee int `json:"penalty_fee"` //违约金
}

type PlatformDispatch struct {
	Platform
	DeliveryOrderNo string `json:"delivery_order_no"` //配送平台单号
}

type PlatformPenalty struct {
	Platform
	Return
	PenaltyFee int `json:"penalty_fee"` //违约金
}

type PlatformQuota struct {
	Platform
	Price     int    `json:"price"`     // 配送费 分
	Distance  int    `json:"distance"`  // 距离 米
	Available int    `json:"available"` // 是否可接单
	Reason    string `json:"reason"`    // 不可用原因
}

type PriceQuotaReq struct {
	SignType
	OrderNO         string  `json:"order_no"`         //内部单号
	FromAddress     Address `json:"from_address"`     //发货地址
	ToAddress       Address `json:"to_address"`       // 收货地址
	LbsType         int     `json:"lbs_type"`         //坐标系类型
	GoodsType       int     `json:"goods_type"`       // 物品类型
	GoodsWeight     int     `json:"goods_weight"`     // 物品重量
	IsSubscribe     int     `json:"is_subscribe"`     //预约类型 0 立即 1 预约
	SubscribeType   int     `json:"subscribe_type"`   // 预约类型：0实时 1预约取件 2预约送达
	SubscribeTime   int     `json:"subscribe_time"`   // 预约时间戳
	DisableDelivery string  `json:"disable_delivery"` //禁用运力 1,2,3
}

type PriceQuotaResp struct {
	OrderNO   string          `json:"order_no"`
	QuotaList []PlatformQuota `json:"quota_list"` //各平台报价
}

type QueryOrderReq struct {
	SignType
	OrderNO string `path:"order_no"`
}

type QueryOrderResp struct {
	Platform
	OrderNO         string      `json:"order_no"`
	DeliveryOrderNo string      `json:"delivery_order_no"`    //配送订单号
	Status          string      `json:"status"`               // 订单状态
	Note            string      `json:"note"`                 // 订单备注
	DriverInfo      *DriverInfo `json:"driver_info,optional"` //骑手信息
	FeeInfo         *FeeInfo    `json:"fee_info"`
	TimeLine        []TimeLine  `json:"time_line"` //时间线信息
	FromAddress     Address     `json:"from_address"`
	ToAddress       Address     `json:"to_address"`
}

type QueryPenaltyResp struct {
	OrderNo     string            `json:"order_no"`
	PenaltyList []PlatformPenalty `json:"penalty_list"`
}

type Return struct {
	Success string `json:"success"`          //平台状态
	Message string `json:"message",optional` //平台返回信息
}

type SignType struct {
	AppId     string `json:"appId"`
	Timestamp string `json:"timestamp"`
	Data      string `json:"data"`
	Sign      string `json:"sign"`
}

type TimeLine struct {
	Time       int64  `json:"time"`
	StatusNode string `json:"status_node"` //发单/预计到达/达到/完成 时间
}
