// Code generated by goctl. DO NOT EDIT.
// goctl v1.8.5

package types

type HelloRequest struct {
	Name  string `json:"name"`
	Page  int64  `json:"page,default=1,optional"`
	Limit int64  `json:"limit,default=10,optional"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Hello string `json:"hello"`
}
