// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type EmptyType struct {
}

type UUCallbackReq struct {
	OrderCode    string `json:"orderCode,optional"` // UU跑腿订单编号
	OriginId     string `json:"originId,optional"`  // 第三方对接平台订单id
	State        string `json:"state"`              // 回调状态
	StateText    string `json:"stateText"`          // 当前状态说明
	DriverName   string `json:"driverName"`         // 跑男姓名(跑男接单后)
	DriverMobile string `json:"driverMobile"`       // 跑男电话(跑男接单后)
	DriverPhoto  string `json:"driverPhoto"`        // 跑男头像(跑男接单后)
	ChangeTime   string `json:"changeTime"`         // 状态变更时间戳（毫秒）
}

type UUCallbackResp struct {
}
