// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: platform.proto

package server

import (
	"context"

	"chuandao-sails-core/apps/platform-gateway/rpc/internal/logic"
	"chuandao-sails-core/apps/platform-gateway/rpc/internal/svc"
	"chuandao-sails-core/apps/platform-gateway/rpc/platform"
)

type PlatformServer struct {
	svcCtx *svc.ServiceContext
	platform.UnimplementedPlatformServer
}

func NewPlatformServer(svcCtx *svc.ServiceContext) *PlatformServer {
	return &PlatformServer{
		svcCtx: svcCtx,
	}
}

// 获取平台配置
func (s *PlatformServer) GetPlatformConfig(ctx context.Context, in *platform.GetPlatformConfigReq) (*platform.GetPlatformConfigResp, error) {
	l := logic.NewGetPlatformConfigLogic(ctx, s.svcCtx)
	return l.GetPlatformConfig(in)
}
