CREATE TABLE `dispatch_cancel_log`
(
    `id`                     bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `delivery_no`            varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送单号',
    `external_order_no`      varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '外部订单号（调用方传入）',
    `platform_code`          varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '配送平台代码',
    `platform_order_no`      varchar(128) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '平台订单号',
    `cancel_type`            varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '取消类型：USER/PLATFORM/SYSTEM/TIMEOUT',
    `cancel_reason_id`       varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '取消原因ID',
    `cancel_reason`          varchar(500) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '取消原因描述',
    `cancel_operator`        varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '取消操作人',
    `cancel_source`          varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '取消来源：API/CALLBACK/AUTO',
    `order_status`           varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '取消时订单状态',
    `is_picked`              tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已取件：1是 0否',
    `penalty_fee`            decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '违约金（元）',
    `penalty_rule`           varchar(255) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '违约金规则',
    `is_penalty_paid`        tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已支付违约金：1是 0否',
    `refund_amount`          decimal(10, 2)                           NOT NULL DEFAULT 0.00 COMMENT '退款金额（元）',
    `refund_status`          varchar(32) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '退款状态：PENDING/SUCCESS/FAILED',
    `platform_response_code` varchar(64) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '平台响应码',
    `platform_response_msg`  varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '平台响应消息',
    `is_cancel_success`      tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否取消成功：1成功 0失败',
    `order_created_at`       datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '订单创建时间',
    `cancel_requested_at`    datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '取消请求时间',
    `cancel_confirmed_at`    datetime                                 NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '取消确认时间',
    `extra_data`             json                                     NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `city_code`              varchar(20) COLLATE utf8mb4_unicode_ci   NOT NULL DEFAULT '' COMMENT '城市编码',
    `created_at`             datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`             datetime                                 NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY                      `idx_delivery_no` (`delivery_no`),
    KEY                      `idx_external_order` (`external_order_no`),
    KEY                      `idx_platform_order` (`platform_code`, `platform_order_no`),
    KEY                      `idx_cancel_type` (`cancel_type`),
    KEY                      `idx_is_cancel_success` (`is_cancel_success`),
    KEY                      `idx_city_created` (`city_code`, `created_at`),
    KEY                      `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单取消记录表';