CREATE TABLE platform_push_order_master
(
    id                bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    order_no          varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '系统内部订单号',
    upstream_order_id varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '上游平台订单号',
    platform_code     varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '平台标识：UU/SF/CHD',
    order_source      varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '订单来源：MT/SG/EL/JDDJ等',
    order_num         varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '订单流水号',
    city_name         varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '城市名称',
    county_name       varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '县级地名称',
    ad_code           varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '城市编码（高德规范）',
    send_type         tinyint(1) NOT NULL DEFAULT 0 COMMENT '订单小类：0帮我送 1帮我买 2帮我取',
    delivery_type     varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '配送类型：1团送 2专送',
    is_reverse_order  tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否帮我取订单：1是 0否',
    push_type         tinyint(1) NOT NULL DEFAULT 0 COMMENT '推送类型：0正常 1测试',
    from_address      json NOT NULL COMMENT '发货地址信息',
    to_address        json NOT NULL COMMENT '收货地址信息',
    order_time        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '订单时间',
    is_subscribe      tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否预约单：1是 0否',
    subscribe_type    tinyint(1) NOT NULL DEFAULT 0 COMMENT '预约类型：0实时 1预约取件 2预约送达',
    subscribe_time    bigint NOT NULL DEFAULT 0 COMMENT '预约时间戳',
    goods_info        json NOT NULL COMMENT '商品详情信息',
    price_info        json NOT NULL COMMENT '价格信息',
    delivery_options  json NOT NULL COMMENT '配送选项',
    note              text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '备注信息',
    disable_delivery  varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '禁用配送方',
    status            tinyint(1) NOT NULL DEFAULT 1 COMMENT '状态：1待处理 2已转换 3处理失败',
    error_msg         text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '错误信息',
    retry_count       tinyint NOT NULL DEFAULT 0 COMMENT '重试次数',
    city_code         varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '城市编码(二级分区 List Default Hash)',
    created_at        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间(一级分区 Interval_Range)',
    updated_at        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id) USING BTREE,
    UNIQUE INDEX uk_upstream_order_platform(upstream_order_id) USING BTREE,
    INDEX idx_upstream_order_id(upstream_order_id ASC) USING BTREE,
    INDEX idx_order_no(order_no ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '平台推单主表' ROW_FORMAT = Dynamic;