CREATE TABLE `track_order_track_log`
(
    `id`                bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `delivery_no`       varchar(64) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '配送单号',
    `external_order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '外部订单号',
    `platform_code`     varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '配送平台代码',
    `platform_order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '平台订单号',
    `track_type`        varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '轨迹类型：STATUS/LOCATION/TIMELINE/EXCEPTION',
    `order_status`      varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '订单状态',
    `status_desc`       varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '状态描述',
    `status_time`       datetime                                NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '状态时间',
    `latitude`          decimal(10, 6)                          NOT NULL DEFAULT 0.000000 COMMENT '纬度',
    `longitude`         decimal(10, 6)                          NOT NULL DEFAULT 0.000000 COMMENT '经度',
    `address`           varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '地址描述',
    `location_time`     datetime                                NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '位置时间',
    `courier_name`      varchar(64) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '骑手姓名',
    `courier_phone`     varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '骑手电话',
    `courier_info`      json                                    NOT NULL DEFAULT '{}' COMMENT '骑手详情',
    `operator`          varchar(64) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '操作人',
    `operator_type`     varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '操作类型：PLATFORM/SYSTEM/COURIER/USER',
    `operation_desc`    varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '操作描述',
    `data_source`       varchar(32) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '数据来源：CALLBACK/POLLING/MANUAL',
    `source_time`       datetime                                NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '数据源时间',
    `photo_urls`        json                                    NOT NULL DEFAULT '[]' COMMENT '照片URL列表',
    `extra_data`        json                                    NOT NULL DEFAULT '{}' COMMENT '扩展数据',
    `city_code`         varchar(20) COLLATE utf8mb4_unicode_ci  NOT NULL DEFAULT '' COMMENT '城市编码',
    `created_at`        datetime                                NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY                 `idx_delivery_no` (`delivery_no`, `created_at`),
    KEY                 `idx_external_order` (`external_order_no`),
    KEY                 `idx_platform_order` (`platform_code`, `platform_order_no`),
    KEY                 `idx_track_type` (`track_type`),
    KEY                 `idx_order_status` (`order_status`),
    KEY                 `idx_status_time` (`status_time`),
    KEY                 `idx_location_time` (`location_time`),
    KEY                 `idx_city_created` (`city_code`, `created_at`),
    KEY                 `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单轨迹追踪表';